
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-1
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NTIxMjQ5","is_bot":false,"login":"cameron-barrett","name":"Cameron Barrett"},"headRefName":"revert-26-Ricardo-RestaurantFrontend","number":27,"title":"Revert \"Added rest of Restaurant frontend files\"","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-1/pull/27"}]
