
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-1
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjYwMTI0ODcz","is_bot":false,"login":"b4k3s","name":""},"headRefName":"Christian-CopyFrontendFiles","number":13,"title":"cjb - add files from the frontend in team01","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-1/pull/13"}]
